#  Programs

$terminal = alacritty

$fileManager = thunar

$menu = fuzzel

$calculator = gnome-calculator

$notes = nvl ~/Notes

$musicPlayer = chromium-browser --app=http://localhost:5173/

$browser = zen-beta

$passwordManager = bitwarden
