# Window Rules

windowrule {
  name = 
  match:class = 
  float = on
  center = on
  size = 
}

windowrule {
  name = nvim
  match:class = nvim
  float = on
  center = on
  size = monitor_w*0.5 monitor_h*0.9
}

windowrule {
  name = portal
  match:class = xdg-desktop-portal-gtk
  float = on
  center = on
  size = monitor_w*0.5 monitor_h*0.75
}

windowrule {
  name = Vellum
  match:class = chrome-localhost__-Default
  fullscreen = on
}

windowrule {
  name = fullscreen_programs
  match:class = ^(imv|mpv|rmpc)$
  fullscreen = on
}

windowrule {
  name = bitwarden
  match:class = Bitwarden
  float = on
  center = on
  size = monitor_w*0.6 monitor_h*0.75
}

windowrule {
  name = thunar
  match:class = ^(thunar|Thunar)$
  float = on
  center = on
  size = monitor_w*0.5 monitor_h*0.75
}

windowrule {
  name = calculator
  match:class = org.gnome.Calculator
  float = on
  pin = on
  size = 360 540
  move = 1500 110
}
