# configuration #

[main]
shell=/run/current-system/sw/bin/fish
dpi-aware=yes
font=CommitMonoNerd Font:size=10
line-height=14
pad = 16x16 center

[cursor]
style=beam

[colors]

cursor=CCCCCC CCCCCC

alpha=0.95
background=111111
foreground=CCCCCC

regular0=333333
regular1=EA4335
regular2=34A853
regular3=FBBC04
regular4=4285F4
regular5=A142F4
regular6=4285F4
regular7=CCCCCC

bright0=555555 
bright1=EA4335 
bright2=34A853 
bright3=FBBC04
bright4=4285F4 
bright5=A142F4
bright6=4285F4 
bright7=CCCCCC 
